### PR TITLE
Improvements for older devices.

### PR DESCRIPTION
**Pull request by kalaspuffar**
Hi @alexhauser 

I thought it was easier to do a pull request.

Tried the code on my Samsung S5 and it crashed over and over because of compat issues.

This code works as I use the srcCompat to load the resources and then switch between different ImageViews perhaps there is a more pretty solution but at least this works :)

Best regards
Daniel

### CODE REVIEW

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

Did you see this one?

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @kalaspuffar ,

wow, I was baffled because I didn't see the PR anywhere after I've got the email notification, because I didn't realize it was in MY repo, not in yours! 🙊

Will look at it tonight or tomorrow morning, gotta head out now.

Best regards,
Alex

**Comment by alexhauser** [comment]
Hi @kalaspuffar ,

thanks for testing and finding my bugs, very much appreciated! Stupid mistake of mine too, using `tools:srcCompat` instead of `app:srcCompat`.

Any specific reason why you chose to add a second image and then toggle the visibility of the images? I found that only swapping out the drawable still works fine when using `app:srcCompat`.

Best regards,
Alex

**Comment by alexhauser** [comment]
Hi @kalaspuffar ,

testing on API 16 reveals the problem and I can now see why you've done what you've done. I'll investigate a little further and get back asap.

Best regards,
Alex

**Comment by alexhauser** [comment]
Hi again @kalaspuffar ,

turns out that adding `AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);`  to onCreate of our Application class correctly initializes the vector drawables support library, and with that change together with having all the drawable sources set with `app:srcCompat`  everything works as expected.

Will post a PR with those changes now.

Thanks again and best regards,
Alex

**Pull request closed without merging**
